title: Anirudh Manikonda
logo: assets/img/2x2 Photo.jpg
Descriptions: Java Developer | 7+ yrs experience | Spring Boot, React.js, Microservices, CI/CD, AWS | Building scalable, user-focused solutions.
show_downloads: True
theme: jekyll-theme-minimal
